var global = {
	stage:null,
	camera:null,
	canvas:null,
	gameWidth:0,
	gameHeight:0,
	levelWidth:1500,
	levelHeight:1500,
	preloader : null,
	sceneController : null,
	keyboard: null,
	hero: null,
	EnemyManager: null,
	BulletFactory: null,
	BonusManager: null,
	staticControl : false,
	gameTime : 0,
	points : 0,
	place : 0,
	music : null,
	volumePanel : null,
	soundManager : null
};
